### ISSUE TITLE
Librtmp compilation issue

### ISSUE THREAD

**Issue by badr-badri** [badr-badri/zenbuild#1]
Get that error while compiling ffmpeg with librtmp :
libass: build OK
librtmp: building ...
Clonage dans 'rtmpdump'...
remote: Counting objects: 2553, done.
remote: Compressing objects: 100% (914/914), done.
remote: Total 2553 (delta 1926), reused 2149 (delta 1638)
Réception d'objets: 100% (2553/2553), 800.50 KiB | 208.00 KiB/s, fait.
Résolution des deltas: 100% (1926/1926), fait.
Vérification de la connectivité... fait.
x86_64-linux-gnu-gcc -Wall   -DRTMPDUMP_VERSION=\"v2.4\" -DNO_CRYPTO  -O2 -fPIC   -c -o rtmp.o rtmp.c
rtmp.c: In function ‘RTMP_ReadPacket’:
rtmp.c:3575:7: warning: variable ‘didAlloc’ set but not used [-Wunused-but-set-variable]
   int didAlloc = FALSE;
       ^
x86_64-linux-gnu-gcc -Wall   -DRTMPDUMP_VERSION=\"v2.4\" -DNO_CRYPTO  -O2 -fPIC   -c -o log.o log.c
x86_64-linux-gnu-gcc -Wall   -DRTMPDUMP_VERSION=\"v2.4\" -DNO_CRYPTO  -O2 -fPIC   -c -o amf.o amf.c
x86_64-linux-gnu-gcc -Wall   -DRTMPDUMP_VERSION=\"v2.4\" -DNO_CRYPTO  -O2 -fPIC   -c -o hashswf.o hashswf.c
x86_64-linux-gnu-gcc -Wall   -DRTMPDUMP_VERSION=\"v2.4\" -DNO_CRYPTO  -O2 -fPIC   -c -o parseurl.o parseurl.c
x86_64-linux-gnu-ar rs librtmp.a rtmp.o log.o amf.o hashswf.o parseurl.o
x86_64-linux-gnu-ar: création de librtmp.a
x86_64-linux-gnu-gcc -shared -Wl,--out-implib,librtmp.dll.a  -o librtmp-1.dll rtmp.o log.o amf.o hashswf.o parseurl.o   -lws2_32 -lwinmm -lgdi32
/usr/bin/ld: option « --out-implib » non reocnnue
/usr/bin/ld: utiliser --help pour afficher l'aide-mémoire
collect2: error: ld returned 1 exit status
Makefile:92: recipe for target 'librtmp-1.dll' failed
make: *** [librtmp-1.dll] Error 1

**Comment by rbouqueau** [comment]
You closed the issue. Does it mean you fixed it?

**Comment by badr-badri** [comment]
The issue seems to be fixed.
