### ISSUE TITLE
libass compilation issue

### ISSUE THREAD

**Issue by badr-badri** [badr-badri/zenbuild#2]
While compiling ffmpeg with libass it displays this error :
/usr/bin/ld: /tmp/mplayer1/release/x86_64-linux-gnu/lib/libass.a(ass.o): réadressage de R_X86_64_32 en vertu de « .rodata.str1.8 » ne peut être utilisé lors de la création d'un objet partagé; recompilez avec -fPIC
/tmp/mplayer1/release/x86_64-linux-gnu/lib/libass.a: error adding symbols: Mauvaise valeur
collect2: error: ld returned 1 exit status
/tmp/mplayer1/src/ffmpeg/library.mak:106: recipe for target 'libavfilter/libavfilter.so.4' failed
make: *** [libavfilter/libavfilter.so.4] Error 1
@rbouqueau

**Comment by badr-badri** [comment]
tu as une idée de comment résoudre ce problème ?

**Comment by rbouqueau** [comment]
Is it compiled with --enable-pic?

Can you play with shared libraries vs static ones? For example, you build libass as a static lib, do you also have the issue if you build it as a shared one?

The other option is that the build mixes 32 and 64 bits.

**Comment by badr-badri** [comment]
It's okay now :)
I'm make a commit once I finish some tests

**Comment by rbouqueau** [comment]
Great!
