### ISSUE TITLE
gnutls build for i686-w64-mingw32

### ISSUE THREAD

**Issue by badr-badri** [badr-badri/zenbuild#20]
While compiling gnutls for this archi I get this error  :
checking for NETTLE... yes
checking for HOGWEED... no
configure: error: 
  ***
  *** Libhogweed (nettle's companion library) was not found. Note that you must compile nettle with gmp support.

**Comment by rbouqueau** [comment]
See #21 . You probably try to use a non-dev version of nettle, see http://lists.gnupg.org/pipermail/gnutls-help/2014-August/003567.html.

**Comment by badr-badri** [comment]
I think that it's related to the target architecture because it can be compiled successfully for x86_64-linux-gnu

**Comment by rbouqueau** [comment]
You can get the error message from the config.log message (or any *.log file). What do you see?

**Comment by rbouqueau** [comment]
Already fixed
