### ISSUE TITLE
add opensvc

### ISSUE THREAD

**Issue by rbouqueau** [badr-badri/zenbuild#8]

**Comment by rbouqueau** [comment]
https://sourceforge.net/p/gpac/code/HEAD/tree/trunk/gpac_extra_libs/

**Comment by rbouqueau** [comment]
https://sourceforge.net/p/opensvcdecoder/code/HEAD/tree/

**Comment by rbouqueau** [comment]
I'm still interested in this one also :)

**Comment by badr-badri** [comment]
While I try to compile manually the opensvc I get this error :

Linking C static library libSVC_baseline.a
[ 96%] Built target SVC_baseline
[ 97%] Building C object CommonFiles/src/CMakeFiles/OpenSVCDec.dir/ControlLayer.c.o
[ 98%] Building C object CommonFiles/src/CMakeFiles/OpenSVCDec.dir/display_tcpmp.c.o
[ 98%] Building C object CommonFiles/src/CMakeFiles/OpenSVCDec.dir/H264_plg.c.o
[ 99%] Building C object CommonFiles/src/CMakeFiles/OpenSVCDec.dir/ParseAU.c.o
/home/bbadri/Téléchargements/gpac-code-5619-trunk/gpac_extra_libs/gpac_extra_libs/opensvc/svcsvn/CommonFiles/src/ParseAU.c: In function ‘ParseAuPlayers’:
/home/bbadri/Téléchargements/gpac-code-5619-trunk/gpac_extra_libs/gpac_extra_libs/opensvc/svcsvn/CommonFiles/src/ParseAU.c:177:28: warning: passing argument 2 of ‘decodeNAL’ discards ‘const’ qualifier from pointer target type
    decodeNAL(PlayerStruct, buf + buf_index, nalsize, Picture, Layer);
                            ^
In file included from /home/bbadri/Téléchargements/gpac-code-5619-trunk/gpac_extra_libs/gpac_extra_libs/opensvc/svcsvn/CommonFiles/src/ParseAU.c:35:0:
/home/bbadri/Téléchargements/gpac-code-5619-trunk/gpac_extra_libs/gpac_extra_libs/opensvc/svcsvn/CommonFiles/src/SVCDecoder_ietr_api.h:111:5: note: expected ‘unsigned char *’ but argument is of type ‘const unsigned char *’
 int decodeNAL(void *PlayerStruct, unsigned char* nal, int nal_length, OPENSVCFRAME *Frame, int *LayerCommand); 
     ^
Linking C shared library libOpenSVCDec.so
/usr/bin/ld: ../../SVC/lib_svc/libSVC_baseline.a(macroblock_filter.c.o): réadressage de R_X86_64_32S en vertu de « .data » ne peut être utilisé lors de la création d'un objet partagé; recompilez avec -fPIC
../../SVC/lib_svc/libSVC_baseline.a: error adding symbols: Mauvaise valeur
collect2: error: ld returned 1 exit status
CommonFiles/src/CMakeFiles/OpenSVCDec.dir/build.make:166: recipe for target 'CommonFiles/src/libOpenSVCDec.so' failed
make[2]: *** [CommonFiles/src/libOpenSVCDec.so] Error 1
CMakeFiles/Makefile2:217: recipe for target 'CommonFiles/src/CMakeFiles/OpenSVCDec.dir/all' failed
make[1]: *** [CommonFiles/src/CMakeFiles/OpenSVCDec.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2


The steps that I followed are :
1- In the svcsvn directory I executed cmake command without any options 
2- make 

NB : my arch is X86_64-linux-gnu

**Comment by rbouqueau** [comment]
What's the script for building?

**Comment by badr-badri** [comment]
I didn't create a script yet. I did that manually

**Comment by badr-badri** [comment]
added :)

**Comment by badr-badri** [comment]
it seems okay now

**Comment by rbouqueau** [comment]
great, thanks!
